/**
 * Boot Diagnostics — Post-startup health check for the MoMo Overseer.
 * OUROBOROS Cycle 2: Runs a lightweight mutex lock contention benchmark
 * to establish baseline telemetry on every boot.
 *
 * Generated by OUROBOROS Protocol — 2026-04-10
 */

/**
 * Runs a lightweight lock contention benchmark using a Promise-chaining mutex
 * pattern identical to McpClientManager._connectionMutex.
 *
 * @param concurrency Number of concurrent lock acquisitions
 * @param workMs Simulated work per lock hold
 * @returns Diagnostic summary string for stderr logging
 */
export async function runBootDiagnostics(
  concurrency = 10,
  workMs = 5
): Promise<string> {
  let mutex: Promise<void> = Promise.resolve();
  const waits: number[] = [];
  let seq = 0;

  async function runWithLock(holdMs: number): Promise<void> {
    const reqTime = Date.now();
    const prev = mutex;
    let release!: () => void;
    mutex = new Promise(r => { release = r; });
    await prev.catch(() => {});
    const acqTime = Date.now();
    waits.push(acqTime - reqTime);
    await new Promise(r => setTimeout(r, holdMs));
    seq++;
    release();
  }

  const start = Date.now();
  const promises: Promise<void>[] = [];
  for (let i = 0; i < concurrency; i++) {
    promises.push(runWithLock(workMs));
  }
  await Promise.all(promises);
  const elapsed = Date.now() - start;

  const sorted = [...waits].sort((a, b) => a - b);
  const avg = waits.reduce((s, w) => s + w, 0) / waits.length;
  const p99 = sorted[Math.floor(sorted.length * 0.99)];

  const lines = [
    `[Boot Diagnostics] Mutex Contention Profile:`,
    `  Concurrency: ${concurrency} | Work: ${workMs}ms`,
    `  Avg wait: ${Math.round(avg)}ms | Max: ${Math.max(...waits)}ms | P99: ${p99}ms`,
    `  Total elapsed: ${elapsed}ms | Throughput: ${(concurrency / (elapsed / 1000)).toFixed(1)} ops/sec`,
    `  Verdict: ${avg < workMs * concurrency * 0.8 ? '✅ Healthy' : '⚠️ Elevated contention'}`,
  ];

  return lines.join('\n');
}
